[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "linux-aarch64"]

[feature.jazzy]
channels = ["robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-ros-core = "*"
ros-jazzy-rviz2 = "*"

[feature.humble]
channels = ["robostack-humble"]

[feature.humble.dependencies]
ros-humble-ros-core = "*"
ros-humble-turtlesim = "*"

[environments]
jazzy = ["jazzy"]
default = ["humble"]