on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        environment: [jazzy, default]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi environment
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
            environments: ${{ matrix.environment }}

      - name: Test
        run: pixi run ros2 pkg list